### ISSUE TITLE
domain_net-real 

### ISSUE THREAD

**Issue by Alphasky-s** [AminParvaneh/alpha_mix_active_learning#1]
Excuse me, I notice that you use _labels_train.feather_ file to load the domain_net-real dataset , where can I download this  file? I try to look for it on the official website of DomainNet, but I didn't find it.

**Comment by AminParvaneh** [comment]
Thanks for pointing that out. Please pull the latest update of the repo that uses the _*.txt_ files for the labels from the official website. Please set --data_dir to a folder containing _real_train.txt_, _real_test.txt_ and _real_ folder (all the images).
