### ISSUE TITLE
Predict our own datasets?

### ISSUE THREAD

**Issue by kuzzl** [AminParvaneh/alpha_mix_active_learning#2]
Sorry, but how to predict our own datasets? Can share this code?

**Comment by AminParvaneh** [comment]
To add a new dataset, you should implement your own dataset loader and data handler functions and return them in 'get_dataset' and 'get_handler' in the dataset.py (you can follow examples in the dataset.py file). Also, add specific training hyper-parameters for the new dataset to the train_params_pool in the 'supervised_learning' method.

**Comment by dust-removal** [comment]
> Sorry, but how to predict our own datasets? Can share this code?

Hello, have you successfully implemented training your own data set? Can you share specific methods
