### ISSUE TITLE
confusion about the released code

### ISSUE THREAD

**Issue by UnpureRationalist** [AminParvaneh/alpha_mix_active_learning#3]
Thanks for your exciting work, it really helps me a lot. When I read the code, I found a line of code that confused me: 

https://github.com/AminParvaneh/alpha_mix_active_learning/blob/073b73dd4543367156c563962d520bf93a195efa/main.py#L558

maybe it should be like:
```
    if strategy_name == 'CDALSampling':
        ...
```
instead of:
```
    if args.strategy == 'CDALSampling':
        ...
```
Looking forward to your reply. Thank you.

**Comment by AminParvaneh** [comment]
Thanks for pointing that out. This only makes trouble when args.strategy is set to 'All', which executes all the baselines sequentially. we consider that in the latest update.
